# Generated by Django 5.0.4 on 2024-04-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='shippingDetails',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='building_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='cod',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='condition',
            field=models.BooleanField(choices=[(True, 'Delivered'), (False, 'Not Delivered')], default=False),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='content',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='government',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', 'Giza'), ('Sharqia', 'Sharqia'), ('Qalyubia', 'Qalyubia'), ('Ismailia', 'Ismailia'), ('Suez', 'Suez'), ('Dakahlia', 'Dakahlia'), ('Beheira', 'Beheira'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Beni Suef', 'Beni Suef'), ('Faiyum', 'Faiyum'), ('Gharbia', 'Gharbia'), ('Luxor', 'Luxor'), ('Matrouh', 'Matrouh'), ('Minya', 'Minya'), ('Monufia', 'Monufia'), ('New Valley', 'New Valley'), ('North Sinai', 'North Sinai'), ('Port Said', 'Port Said'), ('Qena', 'Qena'), ('Red Sea', 'Red Sea'), ('Sohag', 'Sohag'), ('South Sinai', 'South Sinai'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Damietta', 'Damietta')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='streetName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingDetails',
        ),
    ]
