# Generated by Django 5.0.4 on 2024-04-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_clientdata_shippingdetails_and_more'),
        ('shipper', '0005_wallet_shipper_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper'),
        ),
    ]
