# Generated by Django 5.0.4 on 2024-04-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0002_wallet_alter_shipper_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipper',
            old_name='wallet_balance',
            new_name='wallet',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='transfer_type',
        ),
    ]
